/* Generated By:JJTree: Do not edit this line. ASTAnyType.java */

package com.k_int.codec.comp;

import java.io.Writer;

public class ASTAnyType extends SimpleNode {
  public ASTAnyType(int id) {
    super(id);
  }

  public ASTAnyType(AsnParser p, int id) {
    super(p, id);
  }

  public void outputElementEncoderLine(Writer content_encoder,
                                       String element_name,
                                       int i,
                                       boolean optional)
  {
    // Params for func are :BigInteger component, int tagmode, int tag, 
    //                      boolean optional, boolean is_explicit, OutputStream out

    try
    {
      content_encoder.write("        // placeholder for outputElementEncoderLine in ASTAnyType\n");
    }
    catch ( Exception e )
    {
      e.printStackTrace();
      System.exit(1);
    }

  }
}
