/* Generated By:JJTree: Do not edit this line. ASTClass.java */

package com.k_int.codec.comp;

public class ASTClass extends SimpleNode {

  public int tag_class;

  public ASTClass(int id) {
    super(id);
  }

  public ASTClass(AsnParser p, int id) {
    super(p, id);
  }

}
