/* Generated By:JJTree: Do not edit this line. ASTClassNumber.java */

package com.k_int.codec.comp;

public class ASTClassNumber extends SimpleNode {

  public int which;

  public ASTnumber getNumber()
  {
    if ( which == 1 )
      return (ASTnumber)jjtGetChild(0);

    return null;
  }

  public ASTDefinedValue getDefinedValue()
  {
    if ( which == 2 )
      return (ASTDefinedValue)jjtGetChild(0);

    return null;
  }

  public ASTClassNumber(int id) {
    super(id);
  }

  public ASTClassNumber(AsnParser p, int id) {
    super(p, id);
  }

}
