/* Generated By:JJTree: Do not edit this line. ASTDefinedType.java */

package com.k_int.codec.comp;

import java.io.FileWriter;
import java.io.StringWriter;
import java.io.Writer;

public class ASTDefinedType extends SimpleNode {


  public ASTDefinedType(int id) {
    super(id);
  }

  public ASTDefinedType(AsnParser p, int id) {
    super(p, id);
  }

  public ASTmodulereference getModuleReference()
  {
    if ( jjtGetNumChildren() == 2 )
      return (ASTmodulereference)jjtGetChild(0);
    else
      return null;
  }

  public ASTtypereference getTypeReference()
  {
    if ( jjtGetNumChildren() == 2 )
      return (ASTtypereference)jjtGetChild(1);
    else
      return (ASTtypereference)jjtGetChild(0);
  }


  public String getTypeName()
  {
    ASTmodulereference modref = getModuleReference();
    ASTtypereference typeref = getTypeReference();

    return( null != modref ? ( modref.module_ref + " " ) : "" ) + typeref.typeref;
  }

  public void pass1()
  {
    int i, k = jjtGetNumChildren();

    for (i = 0; i < k; i++)
    {
      Node o = jjtGetChild(i);
      o.pass1();
    }
  }

}
