/* Generated By:JJTree: Do not edit this line. ASTDefinedValue.java */

package com.k_int.codec.comp;

public class ASTDefinedValue extends SimpleNode {
  public ASTDefinedValue(int id) {
    super(id);
  }

  public ASTDefinedValue(AsnParser p, int id) {
    super(p, id);
  }

}
