/* Generated By:JJTree: Do not edit this line. ASTElementTypeList.java */

package com.k_int.codec.comp;

public class ASTElementTypeList extends SimpleNode {
  public ASTElementTypeList(int id) {
    super(id);
  }

  public ASTElementTypeList(AsnParser p, int id) {
    super(p, id);
  }

}
