/* Generated By:JJTree: Do not edit this line. ASTGlobalType.java */

package com.k_int.codec.comp;

public class ASTGlobalType extends SimpleNode {

  public int which = 0;

  public ASTGlobalType(int id) {
    super(id);
  }

  public ASTGlobalType(AsnParser p, int id) {
    super(p, id);
  }

  public String getTypeName()
  {
    switch( which )
    {
      case 1:
        return ((ASTType)jjtGetChild(0)).getTypeName();
      case 2:
        return "MACRO";
    }
    return "ERROR";
  }
}
