/* Generated By:JJTree: Do not edit this line. ASTIntegerType.java */

package com.k_int.codec.comp;

import java.io.File;
import java.io.Writer;
import java.io.FileWriter;

public class ASTIntegerType extends SimpleNode {

  public boolean hasnames = false;

  public ASTIntegerType(int id) {
    super(id);
  }

  public ASTIntegerType(AsnParser p, int id) {
    super(p, id);
  }
}
