/* Generated By:JJTree: Do not edit this line. ASTModuleBody.java */

package com.k_int.codec.comp;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;


public class ASTModuleBody extends SimpleNode {

  private Log log = LogFactory.getLog(this.getClass());

  public ASTModuleBody(int id) {
    super(id);
  }

  public ASTModuleBody(AsnParser p, int id) {
    super(p, id);
  }

  public void pass1()
  {
    log.debug("      ASTModuleBody::pass1");
    int i, k = jjtGetNumChildren();
 
    for (i = 0; i < k; i++)
    {
      jjtGetChild(i).pass1();
    }
 
  }                                    
}
