/* Generated By:JJTree: Do not edit this line. ASTNumberForm.java */

package com.k_int.codec.comp;

public class ASTNumberForm extends SimpleNode {
  public ASTNumberForm(int id) {
    super(id);
  }

  public ASTNumberForm(AsnParser p, int id) {
    super(p, id);
  }

}
