/* Generated By:JJTree: Do not edit this line. ASTNameAndNumberForm.java */

package com.k_int.codec.comp;

public class ASTNameAndNumberForm extends SimpleNode {
  public ASTNameAndNumberForm(int id) {
    super(id);
  }

  public ASTNameAndNumberForm(AsnParser p, int id) {
    super(p, id);
  }

}
