/* Generated By:JJTree: Do not edit this line. ASTNamedConstraint.java */

package com.k_int.codec.comp;

public class ASTNamedConstraint extends SimpleNode {
  public ASTNamedConstraint(int id) {
    super(id);
  }

  public ASTNamedConstraint(AsnParser p, int id) {
    super(p, id);
  }

}
