/* Generated By:JJTree: Do not edit this line. ASTNamedNumber.java */

package com.k_int.codec.comp;

public class ASTNamedNumber extends SimpleNode {

  public int which = 0;

  public ASTNamedNumber(int id) {
    super(id);
  }

  public ASTNamedNumber(AsnParser p, int id) {
    super(p, id);
  }

}
