/* Generated By:JJTree: Do not edit this line. ASTNullValue.java */

package com.k_int.codec.comp;

public class ASTNullValue extends SimpleNode {
  public ASTNullValue(int id) {
    super(id);
  }

  public ASTNullValue(AsnParser p, int id) {
    super(p, id);
  }

}
