/* Generated By:JJTree: Do not edit this line. ASTObjIdComponentList.java */

package com.k_int.codec.comp;

public class ASTObjIdComponentList extends SimpleNode {
  public ASTObjIdComponentList(int id) {
    super(id);
  }

  public ASTObjIdComponentList(AsnParser p, int id) {
    super(p, id);
  }

}
