/* Generated By:JJTree: Do not edit this line. ASTPresenceConstraint.java */

package com.k_int.codec.comp;

public class ASTPresenceConstraint extends SimpleNode {
  public ASTPresenceConstraint(int id) {
    super(id);
  }

  public ASTPresenceConstraint(AsnParser p, int id) {
    super(p, id);
  }

}
