/* Generated By:JJTree: Do not edit this line. ASTSubtypeValueSet.java */

package com.k_int.codec.comp;

public class ASTSubtypeValueSet extends SimpleNode {
  public ASTSubtypeValueSet(int id) {
    super(id);
  }

  public ASTSubtypeValueSet(AsnParser p, int id) {
    super(p, id);
  }

}
