/* Generated By:JJTree: Do not edit this line. ASTskip_to_matching_brace.java */

package com.k_int.codec.comp;

public class ASTskip_to_matching_brace extends SimpleNode {
  public ASTskip_to_matching_brace(int id) {
    super(id);
  }

  public ASTskip_to_matching_brace(AsnParser p, int id) {
    super(p, id);
  }

}
