/* Generated By:JJTree: Do not edit this line. ASTSubtypeSpec.java */

package com.k_int.codec.comp;

public class ASTSubtypeSpec extends SimpleNode {
  public ASTSubtypeSpec(int id) {
    super(id);
  }

  public ASTSubtypeSpec(AsnParser p, int id) {
    super(p, id);
  }
}
