/* Generated By:JJTree: Do not edit this line. ASTSnmpStatus.java */

package com.k_int.codec.comp;

public class ASTSnmpStatus extends SimpleNode {
  public ASTSnmpStatus(int id) {
    super(id);
  }

  public ASTSnmpStatus(AsnParser p, int id) {
    super(p, id);
  }

}
