/* Generated By:JJTree: Do not edit this line. ASTSubtypeValueSetList.java */

package com.k_int.codec.comp;

public class ASTSubtypeValueSetList extends SimpleNode {
  public ASTSubtypeValueSetList(int id) {
    super(id);
  }

  public ASTSubtypeValueSetList(AsnParser p, int id) {
    super(p, id);
  }

}
