/* Generated By:JJTree: Do not edit this line. ASTSingleValue.java */

package com.k_int.codec.comp;

public class ASTSingleValue extends SimpleNode {
  public ASTSingleValue(int id) {
    super(id);
  }

  public ASTSingleValue(AsnParser p, int id) {
    super(p, id);
  }

}
