/* Generated By:JJTree: Do not edit this line. ASTTypeOrValue.java */

package com.k_int.codec.comp;

public class ASTTypeOrValue extends SimpleNode {
  public ASTTypeOrValue(int id) {
    super(id);
  }

  public ASTTypeOrValue(AsnParser p, int id) {
    super(p, id);
  }

}
