/* Generated By:JJTree: Do not edit this line. ASTType.java */

package com.k_int.codec.comp;

import java.io.File;
import java.io.FileWriter;
import java.io.Writer;

public class ASTType extends SimpleNode {

  public int which = 0;

  public ASTType(int id) {
    super(id);
  }

  public ASTType(AsnParser p, int id) {
    super(p, id);
  }

  public String getTypeName()
  {
    switch ( which )
    {
      case 1:
        return ((ASTBuiltinType)jjtGetChild(0)).getTypeName();
      case 2:
        return ((ASTDefinedType)jjtGetChild(0)).getTypeName();
    }
    return "Error";
  }

  // Figure out what class will be used to hold a type
  // public String getBaseClassName(String element_name)
  // {
  //   if ( which == 1 )
  //     return ((ASTBuiltinType)jjtGetChild(0)).getBaseClassName(element_name);

  //   return ((ASTDefinedType)jjtGetChild(0)).getBaseClassName(element_name);
  // }
}
