/* Generated By:JJTree: Do not edit this line. ASTValueRange.java */

package com.k_int.codec.comp;

public class ASTValueRange extends SimpleNode {
  public ASTValueRange(int id) {
    super(id);
  }

  public ASTValueRange(AsnParser p, int id) {
    super(p, id);
  }

}
