/* Generated By:JJTree: Do not edit this line. AsnParserTreeConstants.java */

package com.k_int.codec.comp;

public interface AsnParserTreeConstants
{
  public int JJTINPUT = 0;
  public int JJTMODULEDEFINITION = 1;
  public int JJTTAGDEFAULT = 2;
  public int JJTMODULEIDENTIFIER = 3;
  public int JJTASSIGNEDIDENTIFIER = 4;
  public int JJTMODULEBODY = 5;
  public int JJTEXPORTS = 6;
  public int JJTSYMBOLSEXPORTED = 7;
  public int JJTEXPORTSYMBOLLIST = 8;
  public int JJTIMPORTS = 9;
  public int JJTSYMBOLSIMPORTED = 10;
  public int JJTSYMBOLSFROMMODULELIST = 11;
  public int JJTSYMBOLSFROMMODULE = 12;
  public int JJTSYMBOLLIST = 13;
  public int JJTSYMBOL = 14;
  public int JJTASSIGNMENTLIST = 15;
  public int JJTASSIGNMENT = 16;
  public int JJTMACRODEFINITION = 17;
  public int JJTMACROBODY = 18;
  public int JJTMACROREFERENCE = 19;
  public int JJTTYPEASSIGNMENT = 20;
  public int JJTGLOBALTYPE = 21;
  public int JJTTYPE = 22;
  public int JJTDEFINEDTYPE = 23;
  public int JJTBUILTINTYPE = 24;
  public int JJTENUMERATEDTYPE = 25;
  public int JJTINTEGERTYPE = 26;
  public int JJTBITSTRINGTYPE = 27;
  public int JJTNAMEDNUMBERLIST = 28;
  public int JJTNAMEDNUMBER = 29;
  public int JJTSIGNEDNUMBER = 30;
  public int JJTSETORSEQUENCEOFTYPE = 31;
  public int JJTSETORSEQUENCETYPE = 32;
  public int JJTCHOICETYPE = 33;
  public int JJTELEMENTTYPELIST = 34;
  public int JJTELEMENTTYPE = 35;
  public int JJTCOMPONENTSTYPE = 36;
  public int JJTNAMEDTYPE = 37;
  public int JJTSELECTIONTYPE = 38;
  public int JJTTAGGEDTYPE = 39;
  public int JJTTAG = 40;
  public int JJTCLASSNUMBER = 41;
  public int JJTCLASS = 42;
  public int JJTANYTYPE = 43;
  public int JJTSUBTYPESPEC = 44;
  public int JJTSUBTYPEVALUESETLIST = 45;
  public int JJTSUBTYPEVALUESET = 46;
  public int JJTCONTAINEDSUBTYPE = 47;
  public int JJTSINGLEVALUE = 48;
  public int JJTVALUERANGE = 49;
  public int JJTSIZECONSTRAINT = 50;
  public int JJTPERMITTEDALPHABET = 51;
  public int JJTINNERTYPECONSTRAINTS = 52;
  public int JJTSINGLETYPECONSTRAINT = 53;
  public int JJTMULTIPLETYPECONSTRAINTS = 54;
  public int JJTTYPECONSTRAINTS = 55;
  public int JJTNAMEDCONSTRAINT = 56;
  public int JJTCONSTRAINT = 57;
  public int JJTVALUECONSTRAINT = 58;
  public int JJTPRESENCECONSTRAINT = 59;
  public int JJTVALUEASSIGNMENT = 60;
  public int JJTVALUE = 61;
  public int JJTDEFINEDVALUE = 62;
  public int JJTBUILTINVALUE = 63;
  public int JJTCOMPOUNDVALUE = 64;
  public int JJTSKIP_TO_MATCHING_BRACE = 65;
  public int JJTBOOLEANVALUE = 66;
  public int JJTSPECIALREALVALUE = 67;
  public int JJTNULLVALUE = 68;
  public int JJTNAMEDVALUE = 69;
  public int JJTOBJECTIDENTIFIERVALUE = 70;
  public int JJTOBJIDCOMPONENTLIST = 71;
  public int JJTOBJIDCOMPONENT = 72;
  public int JJTNUMBERFORM = 73;
  public int JJTNAMEANDNUMBERFORM = 74;
  public int JJTBINARYSTRING = 75;
  public int JJTHEXSTRING = 76;
  public int JJTCHARSTRING = 77;
  public int JJTNUMBER = 78;
  public int JJTIDENTIFIER = 79;
  public int JJTMODULEREFERENCE = 80;
  public int JJTTYPEREFERENCE = 81;
  public int JJTDEFINEDMACROTYPE = 82;
  public int JJTDEFINEDMACRONAME = 83;
  public int JJTSNMPOBJECTTYPEMACROTYPE = 84;
  public int JJTSNMPACCESS = 85;
  public int JJTSNMPSTATUS = 86;
  public int JJTSNMPDESCRPART = 87;
  public int JJTSNMPREFERPART = 88;
  public int JJTSNMPINDEXPART = 89;
  public int JJTTYPEORVALUELIST = 90;
  public int JJTTYPEORVALUE = 91;
  public int JJTSNMPDEFVALPART = 92;
  public int JJTTEXTUALCONVENTIONMACROTYPE = 93;
  public int JJTDISPLAYHINT = 94;


  public String[] jjtNodeName = {
    "Input",
    "ModuleDefinition",
    "TagDefault",
    "ModuleIdentifier",
    "AssignedIdentifier",
    "ModuleBody",
    "Exports",
    "SymbolsExported",
    "ExportSymbolList",
    "Imports",
    "SymbolsImported",
    "SymbolsFromModuleList",
    "SymbolsFromModule",
    "SymbolList",
    "Symbol",
    "AssignmentList",
    "Assignment",
    "MacroDefinition",
    "MacroBody",
    "MacroReference",
    "TypeAssignment",
    "GlobalType",
    "Type",
    "DefinedType",
    "BuiltinType",
    "EnumeratedType",
    "IntegerType",
    "BitStringType",
    "NamedNumberList",
    "NamedNumber",
    "SignedNumber",
    "SetOrSequenceOfType",
    "SetOrSequenceType",
    "ChoiceType",
    "ElementTypeList",
    "ElementType",
    "ComponentsType",
    "NamedType",
    "SelectionType",
    "TaggedType",
    "Tag",
    "ClassNumber",
    "Class",
    "AnyType",
    "SubtypeSpec",
    "SubtypeValueSetList",
    "SubtypeValueSet",
    "ContainedSubtype",
    "SingleValue",
    "ValueRange",
    "SizeConstraint",
    "PermittedAlphabet",
    "InnerTypeConstraints",
    "SingleTypeConstraint",
    "MultipleTypeConstraints",
    "TypeConstraints",
    "NamedConstraint",
    "Constraint",
    "ValueConstraint",
    "PresenceConstraint",
    "ValueAssignment",
    "Value",
    "DefinedValue",
    "BuiltinValue",
    "CompoundValue",
    "skip_to_matching_brace",
    "BooleanValue",
    "SpecialRealValue",
    "NullValue",
    "NamedValue",
    "ObjectIdentifierValue",
    "ObjIdComponentList",
    "ObjIdComponent",
    "NumberForm",
    "NameAndNumberForm",
    "BinaryString",
    "HexString",
    "CharString",
    "number",
    "identifier",
    "modulereference",
    "typereference",
    "DefinedMacroType",
    "DefinedMacroName",
    "SnmpObjectTypeMacroType",
    "SnmpAccess",
    "SnmpStatus",
    "SnmpDescrPart",
    "SnmpReferPart",
    "SnmpIndexPart",
    "TypeOrValueList",
    "TypeOrValue",
    "SnmpDefValPart",
    "TextualConventionMacroType",
    "DisplayHint",
  };
}
