/* Generated By:JJTree: Do not edit this line. ASTAssignment.java */

package com.k_int.codec.comp;

public class ASTAssignment extends SimpleNode {
  public ASTAssignment(int id) {
    super(id);
  }

  public ASTAssignment(AsnParser p, int id) {
    super(p, id);
  }

  public void pass1()
  {
    int i, k = jjtGetNumChildren();
 
    for (i = 0; i < k; i++)
    {
      jjtGetChild(i).pass1();
    }
 
  }                                    

}
