/* Generated By:JJTree: Do not edit this line. ASTBitStringType.java */

package com.k_int.codec.comp;

import java.io.Writer;
import java.io.FileWriter;
import java.io.StringWriter;

public class ASTBitStringType extends SimpleNode {

  public boolean hasnames = false;

  public ASTBitStringType(int id) {
    super(id);
  }

  public ASTBitStringType(AsnParser p, int id) {
    super(p, id);
  }
}
