/* Generated By:JJTree: Do not edit this line. ASTBuiltinValue.java */

package com.k_int.codec.comp;

public class ASTBuiltinValue extends SimpleNode {
  public ASTBuiltinValue(int id) {
    super(id);
  }

  public ASTBuiltinValue(AsnParser p, int id) {
    super(p, id);
  }

}
