/* Generated By:JJTree: Do not edit this line. ASTBooleanValue.java */

package com.k_int.codec.comp;

public class ASTBooleanValue extends SimpleNode {
  public ASTBooleanValue(int id) {
    super(id);
  }

  public ASTBooleanValue(AsnParser p, int id) {
    super(p, id);
  }

}
