/* Generated By:JJTree: Do not edit this line. ASTContainedSubtype.java */

package com.k_int.codec.comp;

public class ASTContainedSubtype extends SimpleNode {
  public ASTContainedSubtype(int id) {
    super(id);
  }

  public ASTContainedSubtype(AsnParser p, int id) {
    super(p, id);
  }

}
