/* Generated By:JJTree: Do not edit this line. ASTCharString.java */

package com.k_int.codec.comp;

public class ASTCharString extends SimpleNode {
  public ASTCharString(int id) {
    super(id);
  }

  public ASTCharString(AsnParser p, int id) {
    super(p, id);
  }

}
