/* Generated By:JJTree: Do not edit this line. ASTDefinedMacroType.java */

package com.k_int.codec.comp;

public class ASTDefinedMacroType extends SimpleNode {
  public ASTDefinedMacroType(int id) {
    super(id);
  }

  public ASTDefinedMacroType(AsnParser p, int id) {
    super(p, id);
  }

}
