/* Generated By:JJTree: Do not edit this line. ASTDisplayHint.java */

package com.k_int.codec.comp;

public class ASTDisplayHint extends SimpleNode {
  public ASTDisplayHint(int id) {
    super(id);
  }

  public ASTDisplayHint(AsnParser p, int id) {
    super(p, id);
  }

}
