/* Generated By:JJTree: Do not edit this line. ASTExports.java */

package com.k_int.codec.comp;

public class ASTExports extends SimpleNode {
  public ASTExports(int id) {
    super(id);
  }

  public ASTExports(AsnParser p, int id) {
    super(p, id);
  }

}
