/* Generated By:JJTree: Do not edit this line. ASTExportSymbolList.java */

package com.k_int.codec.comp;

public class ASTExportSymbolList extends SimpleNode {
  public ASTExportSymbolList(int id) {
    super(id);
  }

  public ASTExportSymbolList(AsnParser p, int id) {
    super(p, id);
  }

}
