/* Generated By:JJTree: Do not edit this line. ASTInput.java */

package com.k_int.codec.comp;

public class ASTInput extends SimpleNode {
  public ASTInput(int id) {
    super(id);
  }

  public ASTInput(AsnParser p, int id) {
    super(p, id);
  }

  public void pass1()
  {
     System.err.println("  ASTInput::pass1");

     int i, k = jjtGetNumChildren();

     for (i = 0; i < k; i++)
     {
        jjtGetChild(i).pass1();
     }
  }
}
