/* Generated By:JJTree: Do not edit this line. ASTMacroBody.java */

package com.k_int.codec.comp;

public class ASTMacroBody extends SimpleNode {
  public ASTMacroBody(int id) {
    super(id);
  }

  public ASTMacroBody(AsnParser p, int id) {
    super(p, id);
  }

}
