/* Generated By:JJTree: Do not edit this line. ASTPermittedAlphabet.java */

package com.k_int.codec.comp;

public class ASTPermittedAlphabet extends SimpleNode {
  public ASTPermittedAlphabet(int id) {
    super(id);
  }

  public ASTPermittedAlphabet(AsnParser p, int id) {
    super(p, id);
  }

}
