/* Generated By:JJTree: Do not edit this line. ASTSignedNumber.java */

package com.k_int.codec.comp;

public class ASTSignedNumber extends SimpleNode {

  public String number;
  public boolean is_neg;

  public ASTSignedNumber(int id) {
    super(id);
  }

  public ASTSignedNumber(AsnParser p, int id) {
    super(p, id);
  }
}
