/* Generated By:JJTree: Do not edit this line. ASTSingleTypeConstraint.java */

package com.k_int.codec.comp;

public class ASTSingleTypeConstraint extends SimpleNode {
  public ASTSingleTypeConstraint(int id) {
    super(id);
  }

  public ASTSingleTypeConstraint(AsnParser p, int id) {
    super(p, id);
  }

}
