/* Generated By:JJTree: Do not edit this line. ASTSymbol.java */

package com.k_int.codec.comp;

public class ASTSymbol extends SimpleNode {

  public int which = 0;

  public ASTSymbol(int id) {
    super(id);
  }

  public ASTSymbol(AsnParser p, int id) {
    super(p, id);
  }

}
