/* Generated By:JJTree: Do not edit this line. ASTSnmpAccess.java */

package com.k_int.codec.comp;

public class ASTSnmpAccess extends SimpleNode {
  public ASTSnmpAccess(int id) {
    super(id);
  }

  public ASTSnmpAccess(AsnParser p, int id) {
    super(p, id);
  }

}
