/* Generated By:JJTree: Do not edit this line. ASTSnmpReferPart.java */

package com.k_int.codec.comp;

public class ASTSnmpReferPart extends SimpleNode {
  public ASTSnmpReferPart(int id) {
    super(id);
  }

  public ASTSnmpReferPart(AsnParser p, int id) {
    super(p, id);
  }

}
