/* Generated By:JJTree: Do not edit this line. ASTSetOrSequenceOfType.java */

package com.k_int.codec.comp;

import java.io.Writer;
import java.io.FileWriter;

public class ASTSetOrSequenceOfType extends SimpleNode {

  public int which = 0;
  public boolean has_size_constraint = false;

  public ASTSetOrSequenceOfType(int id) {
    super(id);
  }

  public ASTSetOrSequenceOfType(AsnParser p, int id) {
    super(p, id);
  }
}
