/* Generated By:JJTree: Do not edit this line. ASTSnmpDescrPart.java */

package com.k_int.codec.comp;

public class ASTSnmpDescrPart extends SimpleNode {
  public ASTSnmpDescrPart(int id) {
    super(id);
  }

  public ASTSnmpDescrPart(AsnParser p, int id) {
    super(p, id);
  }

}
