/* Generated By:JJTree: Do not edit this line. ASTSymbolList.java */

package com.k_int.codec.comp;

public class ASTSymbolList extends SimpleNode {
  public ASTSymbolList(int id) {
    super(id);
  }

  public ASTSymbolList(AsnParser p, int id) {
    super(p, id);
  }

}
