/* Generated By:JJTree: Do not edit this line. ASTSymbolsFromModule.java */

package com.k_int.codec.comp;

public class ASTSymbolsFromModule extends SimpleNode {
  public ASTSymbolsFromModule(int id) {
    super(id);
  }

  public ASTSymbolsFromModule(AsnParser p, int id) {
    super(p, id);
  }

  public void pass1()
  {
    ASTModuleIdentifier mi = (ASTModuleIdentifier)jjtGetChild(1);
    CodecBuilderInfo info = CodecBuilderInfo.getInfo();
    String basepkg = System.getProperty("CodecBasePackage");

    System.err.println("..... ASTSymbolsFromModule from "+mi.getModuleReference().module_ref);

    ASTSymbolList sl = (ASTSymbolList)jjtGetChild(0);

    for (int j=0;j<sl.jjtGetNumChildren();j++)
    {
        ASTSymbol s = (ASTSymbol)sl.jjtGetChild(j);
        if ( s.which == 1 )
        {
            info.registerImport(mi.getModuleReference().module_ref, ((ASTtypereference)(s.jjtGetChild(0))).typeref);
        }
        else
            System.err.println("Symbol which = "+s.which);
    }
  }
}
