/* Generated By:JJTree: Do not edit this line. ASTSpecialRealValue.java */

package com.k_int.codec.comp;

public class ASTSpecialRealValue extends SimpleNode {
  public ASTSpecialRealValue(int id) {
    super(id);
  }

  public ASTSpecialRealValue(AsnParser p, int id) {
    super(p, id);
  }

}
