/* Generated By:JJTree: Do not edit this line. ASTSizeConstraint.java */

package com.k_int.codec.comp;

public class ASTSizeConstraint extends SimpleNode {
  public ASTSizeConstraint(int id) {
    super(id);
  }

  public ASTSizeConstraint(AsnParser p, int id) {
    super(p, id);
  }

}
