/* Generated By:JJTree: Do not edit this line. ASTTaggedType.java */

package com.k_int.codec.comp;

import java.io.Writer;
import java.io.File;
import java.io.FileWriter;

public class ASTTaggedType extends SimpleNode {

  public int imporexp = 0;

  public ASTTaggedType(int id) {
    super(id);
  }

  public ASTTaggedType(AsnParser p, int id) {
    super(p, id);
  }

  public boolean isImplicit()
  {
    return ( imporexp == 1 ? true : false );
  }

  public ASTTag getTag()
  {
    return (ASTTag)jjtGetChild(0);
  }

  public ASTType getType()
  {
    return (ASTType)jjtGetChild(1);
  }

  // public String getBaseClassName(String element_name)
  // {
    // Returnn type of inner tagged object
  //   return getType().getBaseClassName(element_name);
  // }
}
