/* Generated By:JJTree: Do not edit this line. ASTTypeOrValueList.java */

package com.k_int.codec.comp;

public class ASTTypeOrValueList extends SimpleNode {
  public ASTTypeOrValueList(int id) {
    super(id);
  }

  public ASTTypeOrValueList(AsnParser p, int id) {
    super(p, id);
  }

}
