/* Generated By:JJTree: Do not edit this line. ASTTypeAssignment.java */

package com.k_int.codec.comp;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;


public class ASTTypeAssignment extends SimpleNode {

  public ASTtypereference typeref_node = null;
  public ASTGlobalType global_type = null;
  
  private Log log = LogFactory.getLog(this.getClass());

  public ASTTypeAssignment(int id) {
    super(id);
  }

  public ASTTypeAssignment(AsnParser p, int id) {
    super(p, id);
  }

  public void pass1()
  {
    CodecBuilderInfo info = CodecBuilderInfo.getInfo();
    log.debug("        Type Assignment: ");

    int i, k = jjtGetNumChildren();

    typeref_node = (ASTtypereference)jjtGetChild(0);
    global_type = (ASTGlobalType)jjtGetChild(1);

    String type_reference = typeref_node.typeref;

    // We need to register this new type....
    // First off, figure out if it is a tagged type or not.
    if ( global_type.which == 1 )  // Make sure the type is not a MACRO
    {
      // Get hold of the type
      ASTType t = (ASTType) (global_type.jjtGetChild(0));
      info.createTypeInfoFor(type_reference, t);
    }

    // LATER: else throw an exception

  }
}
